name: CI

# on push or commit
on: [push]

jobs:
  test:
    name: 🧪 Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: 👍 Checkout
        uses: actions/checkout@v3

      - name: 💡 Install PNPM
        run: npm install -g pnpm

      - name: ❇️ Setup node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: 📥 Install Dependencies
        run: pnpm install

      - name: 💅 Lint
        run: pnpm lint

      - name: 🧪 Unit Tests and coverage
        run: pnpm test

  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          always-auth: true
          registry-url: "https://registry.npmjs.org"

      - name: 💡 Install PNPM
        run: npm install -g pnpm

      - name: 📥 Install Dependencies
        run: pnpm install

      - name: setup git config
        run: |
          git config user.name "Bot"
          git config user.email ""

      - name: Get run number
        id: run_number
        run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          node -e "
          let pkg = require('./packages/ui/package.json');
          let versionParts = pkg.version.split('.');
          versionParts[2] = '${{ env.RUN_NUMBER }}';
          pkg.version = versionParts.join('.');
          require('fs').writeFileSync('./packages/ui/package.json', JSON.stringify(pkg, null, 2));
          "
        shell: bash

      - name: 🍀 Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc 
          cd packages/ui 
          pnpm publish --no-git-checks

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
