import { readFile, writeFile } from "node:fs/promises";
import { transform } from "typedoc-better-json";

async function processApiJson() {
  // read the JSON file generated by typedoc
  const fileContent = await readFile("api/api.json", "utf8");

  // parse it
  const fileData = JSON.parse(fileContent);

  // transform it
  const transformedData = transform(fileData);

  // save it in file
  await writeFile("api/api-summary.json", JSON.stringify(transformedData, null, 2));
}
processApiJson();
