name: Setup Environment

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        type: string
      pnpm-version:
        description: "pnpm version"
        required: false
        type: string
   

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs['node-version'] }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs['pnpm-version'] }}
          run_install: false

      - name: Install dependencies
        run: pnpm install
